### ISSUE TITLE
bus after login

### ISSUE THREAD

**Issue by zyxcambridge** [Nutlope/notesGPT#25]
![image](https://github.com/Nutlope/notesGPT/assets/1818981/be4d2192-dbe7-4a22-a1d3-09172235cd24)

**Comment by zyxcambridge** [comment]
✓ Ready in 1857ms
 ○ Compiling /middleware ...
 ✓ Compiled /middleware in 810ms (283 modules)
 ○ Compiling / ...
⠹ Preparing Convex functions...
⠸ Checking for index or schema changes...
⠦ Checking for index or schema changes...
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ UserAPI.eval [as request]
 ⨯ Error
    at async Header (./components/ui/Header.tsx:16:18)
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ UserAPI.eval [as request]
 ⨯ Error
    at async Header (./components/ui/Header.tsx:16:18)
digest: "1037097554"
⠧ Checking for index or schema changes...
⠼ Checking for index or schema changes...
⠼ Backfilling indexes and checking that documents match your schema...
⠇ Backfilling indexes and checking that documents match your schema...
⠦ Backfilling indexes and checking that documents match your schema...
 ✓ Compiled /dashboard in 348ms (1418 modules)
✔ 14:50:42 Convex functions ready! (5.54s)
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ UserAPI.eval [as request]
 ⨯ Error
    at async Header (./components/ui/Header.tsx:16:18)
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ UserAPI.eval [as request]
 ⨯ Error
    at async Header (./components/ui/Header.tsx:16:18)
digest: "1037097554"
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
null
 ⨯ node_modules/@clerk/backend/dist/esm/index.js (1330:18) @ SessionAPI.eval [as request]
 ⨯ Error: Not Found
    at async getAuthToken (./app/auth.ts:8:12)
    at async ServerDashboardHomePage (./app/dashboard/page.tsx:17:19)
null

**Comment by rohit-saluja** [comment]
I have just now installed this application fresh I didn't get any of these issues, can you recheck all the points mentioned on the read-me file again?

**Comment by zyxcambridge** [comment]
> I have just now installed this application fresh I didn't get any of these issues, can you recheck all the points mentioned on the read-me file again?

mac m1

**Comment by zyxcambridge** [comment]
https://www.loom.com/share/f8fdfd526310474086624712578de506?sid=5574ba68-ee90-468f-b4ea-ebf6574b4607
